### ISSUE TITLE
Return error code

### ISSUE THREAD

**Issue by MihailRomanov** [Franklin89/NGitLab#20]
Could you return status code if request throw error?
Now I should parse string "The remote server returned an error ({0}): {1}" for get error code (for example, 401 Unauthorized).

**Comment by Scooletz** [comment]
Could you issue a pull request with the proposal of this change?
22 cze 2015 17:44 "MihailRomanov" <notifications@github.com> napisał(a):

**Comment by MihailRomanov** [comment]
Yes, ok.
I think, I can do it on the next week.

Thank, you

**Comment by Scooletz** [comment]
Great!
24 cze 2015 07:34 "MihailRomanov" <notifications@github.com> napisał(a):
