### ISSUE TITLE
[question] [discussion] (N)GitLab queries are slow

### ISSUE THREAD

**Issue by hellboy81** [Franklin89/NGitLab#36]
I am developing GUI Frondend using `NGitLab`.
GitLab queries seems to be slow
Is it `GitLab` issue or `NGitLab`?
How to solve problem?
Cache `(N)GitLab` query results?

**Comment by Scooletz** [comment]
Hi @hellboy81 I think you've pinged me for being a maintainer for this, haven't you? :)
No idea. As NGitLab is really simple, I don't think it's its fault.

**Comment by Franklin89** [comment]
I'll be looking into this while i create the integration tests. Gonna add some performance test too.
